apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
  labels:
    app: bloggingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloggingapp
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
        - name: bloggingapp
          image: snehalatabarenkal/blogging-apps:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-svc
  labels:
    app: bloggingapp
spec:
  type: LoadBalancer
  selector:
    app: bloggingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
